import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Funiro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            {/* Redirect users who are not signed in */}
            <RedirectToSignIn />
          </SignedOut>
          <SignedIn>
            {/* Render the application for authenticated users */}
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}